# Generated by Django 2.0.6 on 2018-08-28 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('event', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='tickets', to='events.Event')),
                ('member', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
