# Generated by Django 2.0.6 on 2018-09-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20180914_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='theme',
            field=models.CharField(blank=True, choices=[('B&M', 'BODY & MIND'), ('ATH', 'ATHLETIC'), ('SE', 'SPECIAL EVENT')], default='tbc', max_length=30, null=True),
        ),
    ]
