# Generated by Django 2.0.6 on 2018-09-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20180918_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='theme',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, choices=[('BODY & MIND', 'B&M'), ('ATHLETIC', 'ATH'), ('SPECIAL EVENT', 'SE')], default='tbc', max_length=30, null=True),
        ),
    ]
