# Generated by Django 2.0.6 on 2018-10-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20180919_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, choices=[('Body & Mind', 'BODY & MIND'), ('Athletic', 'ATHLETIC'), ('Special Event', 'SPECIAL EVENT')], default='tbc', max_length=30, null=True),
        ),
    ]
