# Generated by Django 2.0.6 on 2018-08-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default='select one', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='county',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default='select one', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='postcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='street_address_1',
            field=models.CharField(default='select one', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='street_address_2',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='profile',
            name='town_or_city',
            field=models.CharField(default='select one', max_length=40),
            preserve_default=False,
        ),
    ]
