# Generated by Django 2.0.6 on 2018-09-13 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_subscription_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='street_address_1',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='street_address_2',
            new_name='address_line_2',
        ),
    ]
