# Generated by Django 2.0.6 on 2018-09-13 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180913_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address_line_1',
            new_name='house_or_flat_no',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='address_line_2',
            new_name='street_name',
        ),
    ]
