# Generated by Django 2.0.6 on 2018-09-13 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180913_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='house_or_flat_no',
            new_name='house_no',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='profile_image',
        ),
    ]
