# Generated by Django 2.0.6 on 2018-10-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180913_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='../static/media/images/anonymous.png', null=True, upload_to='avatars'),
        ),
    ]
