# Generated by Django 2.0.6 on 2018-10-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20181008_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='../images/anonymous.png', null=True, upload_to='avatars'),
        ),
    ]
